apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: swiggy-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/suryaparua-official/Swiggy.git
    targetRevision: main
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: swiggy
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
