apiVersion: v1
kind: ConfigMap
metadata:
  name: swiggy-config
  namespace: swiggy
data:
  NODE_ENV: "production"
  AUTH_PORT: "5000"
  RESTAURANT_PORT: "5001"
  UTILS_PORT: "5002"
  REALTIME_PORT: "5004"
  RIDER_PORT: "5005"
  ADMIN_PORT: "5006"
  DB_NAME: "Zomato_Clone"
  PAYMENT_QUEUE: "payment_event"
  RIDER_QUEUE: "rider_queue"
  ORDER_READY_QUEUE: "order_ready_queue"
  # Inter-service URLs (ClusterIP service names)
  AUTH_SERVICE_URL: "http://auth-service:5000"
  RESTAURANT_SERVICE: "http://restaurant-service:5001"
  UTILS_SERVICE: "http://utils-service:5002"
  REALTIME_SERVICE: "http://realtime-service:5004"
  RIDER_SERVICE_URL: "http://rider-service:5005"
  ADMIN_SERVICE_URL: "http://admin-service:5006"
  FRONTEND_URL: "http://frontend-service"
