apiVersion: v1
kind: Secret
metadata:
  name: swiggy-secrets
  namespace: swiggy
type: Opaque
stringData:
  MONGO_URI: "REPLACE_WITH_ACTUAL"
  JWT_SEC: "REPLACE_WITH_ACTUAL"
  INTERNAL_SERVICE_KEY: "REPLACE_WITH_ACTUAL"
  GOOGLE_CLIENT_ID: "REPLACE_WITH_ACTUAL"
  GOOGLE_CLIENT_SECRET: "REPLACE_WITH_ACTUAL"
  CLOUD_NAME: "REPLACE_WITH_ACTUAL"
  CLOUD_API_KEY: "REPLACE_WITH_ACTUAL"
  CLOUD_SECRET_KEY: "REPLACE_WITH_ACTUAL"
  RAZORPAY_KEY_ID: "REPLACE_WITH_ACTUAL"
  RAZORPAY_KEY_SECRET: "REPLACE_WITH_ACTUAL"
  STRIPE_SECRET_KEY: "REPLACE_WITH_ACTUAL"
  STRIPE_PUBLISHABLE_KEY: "REPLACE_WITH_ACTUAL"
  RABBITMQ_URL: "REPLACE_WITH_ACTUAL"
